language: python
python:
  - "2.7"

env:
  matrix:
    - CHECK=pytest
    - CHECK=pylint


# command to install dependencies
install: 
  - "pip install --upgrade setuptools"
  - "pip install --upgrade pip"
  - "pip install -r requirements.txt"

# command to run tests
script:
  - export PYTHONPATH=$PWD/Handler
  - ls $PYTHONPATH
  - if [[ "${CHECK}" == "pytest"  ]];
    then cd Tests && python test_handler.py;
    elif [[ "${CHECK}" == "pylint"  ]];
    then travis_wait 30 ./runPylint.sh;
    fi

## ignore errors for sourcefiles "-i"
after_success:
  - if [[ "${CHECK}" == "pytest"  ]];
    then coveralls -i;
    fi
